mywebserver.yml
---
- hosts: all
  become: yes
  tasks:
   - name: I want to install webserver
     apt:
       name: apache2
       state: present


  -name: I want to install webserver
   service:
     name: apache2
     statue: started